[project]
name = "fraud-detection-system"
version = "0.1.0"
description = "A fraud detection ML system"
readme = "README.md"
authors = [
    { name = "Christian", email = "christian.parodi19@gmail.it" }
]
requires-python = ">=3.11"
dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "scikit-learn",
    "lightgbm",
    "imbalanced-learn",
    "jupyter"
]

[tool.uv]
package = false
